Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/StructInheritance:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    "%":  ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

Layout/IndentHeredoc:
  Enabled: false
