language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.1

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec danger

script:
  - COVERAGE=true bundle exec rake spec

after_script:
  - bundle exec codeclimate-test-reporter
