language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.0
  - 2.1.10
  - 2.3.3
  - 2.4.0

before_install:
  - gem install bundler

before_script:
  - bundle exec danger

script:
  - COVERAGE=true bundle exec rake spec

after_script:
  - bundle exec codeclimate-test-reporter
