language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - bundle exec danger

script:
  - COVERAGE=true bundle exec rake spec

after_script:
  - bundle exec codeclimate-test-reporter
