language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.0
  - 2.1.3
  - 2.3.1

before_script:
  - bundle exec danger

script:
  - COVERAGE=true bundle exec rake spec

after_script:
  - bundle exec codeclimate-test-reporter
